Update ovpn_copy_server_files

diff --git a/bin/ovpn_copy_server_files b/bin/ovpn_copy_server_files
--- a/bin/ovpn_copy_server_files
+++ b/bin/ovpn_copy_server_files
@@ -5,8 +5,8 @@ set -e
 if [ -z "$OPENVPN" ]; then
     export OPENVPN="$PWD"
 fi
-if ! source "$OPENVPN/ovpn_env.sh"; then
-    echo "Could not source $OPENVPN/ovpn_env.sh."
+if ! source "/etc/openvpn/ovpn_env.sh"; then
+    echo "Could not source /etc/openvpn/ovpn_env.sh."
     exit 1
 fi
 
